apiVersion: apps/v1
kind: Deployment
metadata:
  name: shogun-deployment
  labels:
    app: shogun
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shogun
  template:
    metadata:
      labels:
        app: shogun
    spec:
      containers:
        - name: shogun-container
          image: sudharsanan62034/shogun:landing
          imagePullPolicy: Always
          ports:
            - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: shogun-service
spec:
  # Using ClusterIP is standard when using an Ingress.
  # If you really want NodePort, you can change this.
  type: ClusterIP
  selector:
    app: shogun
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: landing-page
spec:
  replicas: 2
  selector:
    matchLabels:
      app: landing-page
  template:
    metadata:
      labels:
        app: landing-page
    spec:
      containers:
        - name: web
          image: nginxdemos/hello
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: landing-page-svc
spec:
  type: ClusterIP
  selector:
    app: landing-page
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80