apiVersion: apps/v1
kind: Deployment
metadata:
  name: shogun-deployment
  labels:
    app: shogun
spec:
  replicas: 2  # Run 2 copies of the app
  selector:
    matchLabels:
      app: shogun
  template:
    metadata:
      labels:
        app: shogun  # This label MUST MATCH the service selector
    spec:
      containers:
        - name: shogun-container
          # Make sure this image is in a public registry
          image: sudharsanan62034/shogun:landing 
          imagePullPolicy: Always
          ports:
            - containerPort: 3000 # The port your app listens on