apiVersion: v1
kind: Service
metadata:
  name: shogun-service
spec:
  type: ClusterIP  # <-- This is the important part
  selector:
    app: shogun     # <-- This MUST MATCH the 'app' label in your deployment
  ports:
    - protocol: TCP
      port: 80 
              # The port inside the cluster (optional to use)
      targetPort: 3000 # The 'containerPort' from your deployment
      
      # Optional: You can specify a port. 
      # If you leave this out, Kubernetes picks a random one.
      # It MUST be in the 30000-32767 range.
      